- name: Install and configure Zabbix server
  hosts: zabbix
  become: yes
  vars:
    mysql_root_password: "StrongPassword123"
    zabbix_db_password: "ZabbixPassword123"

  tasks:
    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-mbstring
          - php-gd
          - php-xml
          - php-bcmath
          - php-ldap
          - php-xmlrpc
          - zip
          - unzip
        state: present
        update_cache: yes

    - name: Download Zabbix repository package
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb

    - name: Install Zabbix repository
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Install Zabbix server, frontend, and agent
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-agent
        state: present
        update_cache: yes

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Zabbix database and user
      mysql_db:
        name: zabbix
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create Zabbix database user
      mysql_user:
        name: zabbix
        password: "{{ zabbix_db_password }}"
        priv: 'zabbix.*:ALL'
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Import initial Zabbix database schema
      mysql_db:
        name: zabbix
        state: import
        target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
        login_user: zabbix
        login_password: "{{ zabbix_db_password }}"

    - name: Configure Zabbix server
      template:
        src: zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart zabbix server

    - name: Configure PHP for Zabbix frontend
      template:
        src: zabbix.conf.j2
        dest: /etc/zabbix/apache.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart apache

    - name: Start and enable Zabbix server and agent
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

  handlers:
    - name: restart zabbix server
      service:
        name: zabbix-server
        state: restarted

    - name: restart apache
      service:
        name: apache2
        state: restarted