- name: Install and configure Zabbix agents
  hosts: webservers:elastic
  become: yes
  vars:
    zabbix_server_ip: "{{ hostvars[groups['zabbix'][0]]['ansible_host'] }}"

  tasks:
    - name: Download Zabbix repository package
      get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb

    - name: Install Zabbix repository
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Configure Zabbix agent
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart zabbix agent

    - name: Start and enable Zabbix agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes

  handlers:
    - name: restart zabbix agent
      service:
        name: zabbix-agent
        state: restarted